---- ServerScriptService/SetVIP.lua

--local Players = game:GetService("Players")
--local DataHandler = require(game.ServerScriptService.UserData.DataHandler)

--Players.PlayerAdded:Connect(function(player)
--	print(player.Name .. " joined")
--	warn("EFOIWJWEFJIEOWEW")
--	local vipStatus = DataHandler.GetAlternativeCurrency(player, "VIPStatus")
--	warn(vipStatus)
--	if vipStatus == 1 then
--		warn("PATH TAKEN")
--		player:SetAttribute("IsVIP", true)
--	else
--		player:SetAttribute("IsVIP", false)
--	end

--	print("IsVIP:", player:GetAttribute("IsVIP"))
--end)
